version: 2
jobs:
  fetch_data:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e2:9e:67:f7:09:88:f1:a0:e1:e8:39:1c:24:e8:b0:0d"
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Generate CSV data
          command: |
            . venv/bin/activate
            python main.py
      - run:
          name: Set Git identity
          command: |
            git config --global user.email "robot@circleci.com"
            git config --global user.name "CircleCI"
      - run:
          name: Push to GitHub
          command: |
            cd ~/repo
            if [ -n "$(git status --porcelain)" ]; then
              git add data
              git commit -m "New data at $(date -u +'%Y-%m-%dT%H:%M:%SZ') [skip ci]"
              git push origin master
            else
              echo "No changes";
            fi

workflows:
  version: 2
  fetch_and_push:
    jobs:
      - fetch_data:
          filters:
            branches:
              only:
                - master
  cron:
    triggers:
      - schedule:
          cron: "15 10,20 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - fetch_data
